# Site settings
name: Carl Chua
title: Carl Chua | Software Engineer
description: Software Engineer. Currently building an AI Platform at BlackRock
url: https://carlchua.github.io/
baseurl: ""
email: carllenard.chua@gmail.com
resume: https://carlchua.github.io/resume.pdf
social:
  - title: email
    url: mailto:carllenard.chua@gmail.com
  - title: github
    url: https://github.com/carlchua
  - title: linkedin
    url: https://www.linkedin.com/in/carl-chua/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
